In [10]:
graph = {
 '1' : ['2','10'],
 '2' : ['3','8'],
 '3' : ['4'],
 '4' : ['5','6','7'],
 '5' : [],
 '6' : [],
 '7' : [],
 '8' : ['9'],
 '9' : [],
 '10' : []
 }
visited = [] # List for visited nodes.
queue = []     #Initialize a queue

def bfs(visited, graph, node): #function for BFS
  visited.append(node)
  queue.append(node)

  while queue:          # Creating loop to visit each node
    m = queue.pop(0) 
    print (m, end = " ") 

    for neighbour in graph[m]:
      if neighbour not in visited:
        visited.append(neighbour)
        queue.append(neighbour)

# Driver Code
print("Following is the Breadth-First Search")
bfs(visited, graph, '1')    # function calling

Following is the Breadth-First Search
1 2 10 3 8 4 9 5 6 7 

In [13]:
# Using a Python dictionary to act as an adjacency list
graph = {
 '5' : ['3','7'],
 '3' : ['2', '4'],
 '7' : ['6'],
 '6': [],
 '2' : ['1'],
 '1':[],
 '4' : ['8'],
 '8' : []
}
visited = set() # Set to keep track of visited nodes of graph.

def dfs(visited, graph, node):  #function for dfs 
    if node not in visited:
        print (node)
        visited.add(node)
        for neighbour in graph[node]:
            dfs(visited, graph, neighbour)

# Driver Code
print("Following is the Depth-First Search")
dfs(visited, graph, '5')

Following is the Depth-First Search
5
3
2
1
4
8
7
6


In [2]:
from queue import PriorityQueue
import matplotlib.pyplot as plt
import networkx as nx
# for implementing BFS | returns path having lowest cost
def best_first_search(source, target, n):
 visited = [0] * n
 visited[source] = True
 pq = PriorityQueue()
 pq.put((0, source))
 while pq.empty() == False:
   u = pq.get()[1]
   print(u, end=" ") # the path having lowest cost
   if u == target:
     break
   for v, c in graph[u]:
     if visited[v] == False:
       visited[v] = True
       pq.put((c, v))
       print()
# for adding edges to graph
def addedge(x, y, cost):
 graph[x].append((y, cost))
 graph[y].append((x, cost))

v = int(input("Enter the number of nodes: "))
graph = [[] for i in range(v)] # undirected Graph
e = int(input("Enter the number of edges: "))
print("Enter the edges along with their weights:")
for i in range(e):
 x, y, z = list(map(int, input().split()))
 addedge(x, y, z)
source = int(input("Enter the Source Node: "))
target = int(input("Enter the Target/Destination Node: "))
print("Path: ", end = "")
best_first_search(source, target, v)

Enter the number of nodes: 4
Enter the number of edges: 5
Enter the edges along with their weights:
0 1 1
0 2 3
0 2 2
0 3 1
0 3 3
Enter the Source Node: 2
Enter the Target/Destination Node: 1
Path: 2 
0 

1 

In [1]:
import numpy as np
import random
from time import sleep
 
def create_board():
 return(np.array([[0, 0, 0],
   [0, 0, 0],
   [0, 0, 0]]))
 
def possibilities(board):
 l = []
 
 for i in range(len(board)):
  for j in range(len(board)):
 
    if board[i][j] == 0:
     l.append((i, j))
 return(l)
 
def random_place(board, player):
 selection = possibilities(board)
 current_loc = random.choice(selection)
 board[current_loc] = player
 return(board)

def row_win(board, player):
  for x in range(len(board)):
    win = True
 
    for y in range(len(board)):
      if board[x, y] != player:
        win = False
        continue
 
    if win == True:
      return(win)
  return(win)
 
def col_win(board, player):
 for x in range(len(board)):
   win = True
 
   for y in range(len(board)):
    if board[y][x] != player:
     win = False
     continue
 
   if win == True:
    return(win)
 return(win)

def diag_win(board, player):
 win = True
 y = 0
 for x in range(len(board)):
  if board[x, x] != player:
    win = False
 if win:
  return win
 win = True
 if win:
   for x in range(len(board)):
    y = len(board) - 1 - x
    if board[x, y] != player:
     win = False
 return win
 
def evaluate(board):
 winner = 0
 
 for player in [1, 2]:
  if (row_win(board, player) or
    col_win(board,player) or 
    diag_win(board,player)): 
    winner = player 
 if np.all(board != 0) and winner == 0:
  winner = -1

  return winner
def play_game():
 board, winner, counter = create_board(), 0, 1
 print(board)
 sleep(2)
 
 while winner == 0:
   for player in [1, 2]:
    board = random_place(board, player)
    print("Board after " + str(counter) + " move")
    print(board)
    sleep(2)
    counter += 1
    winner = evaluate(board)
    if winner != 0:
     break
 return(winner)
print("Winner is: " + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Winner is: None


In [3]:
from collections import defaultdict
jug1, jug2, aim = 5, 7, 4
visited = defaultdict(lambda: False) 
def waterJugSolver(amt1, amt2):
 if (amt1 == aim and amt2 == 0) or (amt2 == aim and amt1 == 0): 
   print(amt1, amt2) 
   return True
 if visited[(amt1, amt2)] == False: 
   print(amt1, amt2)
   visited[(amt1, amt2)] = True 
   return (waterJugSolver(0, amt2) or 
 waterJugSolver(amt1, 0) or
 waterJugSolver(jug1, amt2) or 
 waterJugSolver(amt1, jug2) or 
 waterJugSolver(amt1 + min(amt2, (jug1-amt1)), 
 amt2 - min(amt2, (jug1-amt1))) or 
 waterJugSolver(amt1 - min(amt1, (jug2-amt2)),
 amt2 + min(amt1, (jug2-amt2)))) 
 else: 
   return False 
print("Steps: ") 
waterJugSolver(0, 0) 

Steps: 
0 0
5 0
5 7
0 7
5 2
0 2
2 0
2 7
5 4
0 4


True

In [1]:
# Tic-Tac-Toe Program using
# random number in Python
 
# importing all necessary libraries
import numpy as np
import random
from time import sleep
 
# Creates an empty board
 
 
def create_board():
    return(np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]]))
 
# Check for empty places on board
 
 
def possibilities(board):
    l = []
 
    for i in range(len(board)):
        for j in range(len(board)):
 
            if board[i][j] == 0:
                l.append((i, j))
    return(l)
 
# Select a random place for the player
 
 
def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player
    return(board)
 
# Checks whether the player has three
# of their marks in a horizontal row
 
 
def row_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
 
# Checks whether the player has three
# of their marks in a vertical row
 
 
def col_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
 
# Checks whether the player has three
# of their marks in a diagonal row
 
 
def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win
    win = True
    if win:
        for x in range(len(board)):
            y = len(board) - 1 - x
            if board[x, y] != player:
                win = False
    return win
 
# Evaluates whether there is
# a winner or a tie
 
 
def evaluate(board):
    winner = 0
 
    for player in [1, 2]:
        if (row_win(board, player) or
                col_win(board, player) or
                diag_win(board, player)):
 
            winner = player
 
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner
 
# Main function to start the game
 
 
def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    sleep(2)
 
    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print("Board after " + str(counter) + " move")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    return(winner)
 
 
# Driver Code
print("Winner is: " + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 0]
 [1 0 0]]
Board after 2 move
[[2 0 0]
 [0 0 0]
 [1 0 0]]
Board after 3 move
[[2 1 0]
 [0 0 0]
 [1 0 0]]
Board after 4 move
[[2 1 0]
 [0 0 2]
 [1 0 0]]
Board after 5 move
[[2 1 0]
 [0 0 2]
 [1 0 1]]
Board after 6 move
[[2 1 0]
 [2 0 2]
 [1 0 1]]
Board after 7 move
[[2 1 0]
 [2 0 2]
 [1 1 1]]
Winner is: 1


In [3]:
import copy
from heapq import heappush, heappop
n = 3
row = [ 1, 0, -1, 0 ]
col = [ 0, -1, 0, 1 ]
class priorityQueue:
    def __init__(self):
        self.heap = []
    def push(self, k):
        heappush(self.heap, k)
    def pop(self):
        return heappop(self.heap)
    def empty(self):
        if not self.heap:
            return True
        else:
            return False
class node:
     
    def __init__(self, parent, mat, empty_tile_pos,
                 cost, level):
        self.parent = parent
        self.mat = mat
        self.empty_tile_pos = empty_tile_pos
        self.cost = cost
        self.level = level
    def __lt__(self, nxt):
        return self.cost < nxt.cost
def calculateCost(mat, final) -> int:     
    count = 0
    for i in range(n):
        for j in range(n):
            if ((mat[i][j]) and
                (mat[i][j] != final[i][j])):
                count += 1                 
    return count 
def newNode(mat, empty_tile_pos, new_empty_tile_pos,
            level, parent, final) -> node:
    new_mat = copy.deepcopy(mat) 
    x1 = empty_tile_pos[0]
    y1 = empty_tile_pos[1]
    x2 = new_empty_tile_pos[0]
    y2 = new_empty_tile_pos[1]
    new_mat[x1][y1], new_mat[x2][y2] = new_mat[x2][y2], new_mat[x1][y1]
    cost = calculateCost(new_mat, final)
    new_node = node(parent, new_mat, new_empty_tile_pos,
                    cost, level)
    return new_node
def printMatrix(mat):
    for i in range(n):
        for j in range(n):
            print("%d " % (mat[i][j]), end = " ")             
        print()
def isSafe(x, y):     
    return x >= 0 and x < n and y >= 0 and y < n
def printPath(root):     
    if root == None:
        return     
    printPath(root.parent)
    printMatrix(root.mat)
    print()
def solve(initial, empty_tile_pos, final):
    pq = priorityQueue()
    cost = calculateCost(initial, final)
    root = node(None, initial,
                empty_tile_pos, cost, 0)
    pq.push(root)
    while not pq.empty():
        minimum = pq.pop()
        if minimum.cost == 0:
            printPath(minimum)
            return
        for i in range(n):
            new_tile_pos = [
                minimum.empty_tile_pos[0] + row[i],
                minimum.empty_tile_pos[1] + col[i], ]                 
            if isSafe(new_tile_pos[0], new_tile_pos[1]):
                child = newNode(minimum.mat,
                                minimum.empty_tile_pos,
                                new_tile_pos,
                                minimum.level + 1,
                                minimum, final,)
                pq.push(child)
initial = [ [ 1, 2, 3 ],
            [ 5, 6, 0 ],
            [ 7, 8, 4 ] ]
final = [ [ 1, 2, 3 ],
          [ 5, 8, 6 ],
          [ 0, 7, 4 ] ]
empty_tile_pos = [ 1, 2 ]
solve(initial, empty_tile_pos, final)

1  2  3  
5  6  0  
7  8  4  

1  2  3  
5  0  6  
7  8  4  

1  2  3  
5  8  6  
7  0  4  

1  2  3  
5  8  6  
0  7  4  



In [10]:
from sys import maxsize
from itertools import permutations
V=4

def travellingSalesmanProblem(graph,s):
    vertex=[]
    for i in range(V):
      if i!=s:
        vertex.append(i)
        
    min_path=maxsize
    next_permutation=permutation(vertex)
    for i in next_permutation:
        
        
        
        current_pathweight=0
        
        k=s
        for j in i:
         current_pathweight+=graph[k][j]
         k=j
        current_pathweight +=graph[k][s]
            min_path=min(min_path,current_pathweight)
 return min_path
if __name__=="__main__":
        
        graph=[[0,10,15,20],[10,0,35,25],
              [15,35,0,30],[20,25,30,0]]
        s=0
        print( travellingSalesmanProblem(graph,s))
            
        

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 25)

In [6]:
from sys import maxsize
from itertools import permutations
V = 4

def travellingSalesmanProblem(graph, s):
# store all vertex apart from source vertex
 vertex = []
 for i in range(V):
   if i != s:
    vertex.append(i)

# store minimum weight Hamiltonian Cycle
    min_path = maxsize
    next_permutation=permutations(vertex)
 for i in next_permutation:

# store current Path weight(cost)
        current_pathweight = 0

# compute current path weight
        k = s
        for j in i:
           current_pathweight += graph[k][j]
           k = j
        current_pathweight += graph[k][s]



# Update minimum
        min_path = min(min_path, current_pathweight)
 return min_path

# Driver Code
if __name__ == "__main__":

# matrix representation of graph
 graph = [[0, 10, 15, 20], [10, 0, 35, 25],
          [15, 35, 0, 30], [20, 25, 30, 0]]
s = 0
print(travellingSalesmanProblem(graph, s))

80


In [4]:
import csv
hypo=['%','%','%','%','%','%']
with open('ws.csv') as csv_file:
    readcsv = csv.reader(csv_file, delimiter=',')
data=[]
print("\nThe given training examples are:")
for row in readcsv:
    print(row)
    if row[len(row)-1] =='Yes':
        data.append(row)
        print("\nThe positive examples are:")
        for x in data:
            print(x)
            TotalExamples=len(data)
            i=0
            j=0
            k=0
            print("\nThe steps of the Find-s algorithm are\n",hypo)
            list=[]
            p=0
            d=len(data[p])-1
            for j in range(d):
                list.append(data[i][j])
                hypo=list
                for i in range(1,TotalExamples):
                    for k in range(d):
                        if hypo[k]!=data[i][k]:
                            hypo[k]='?'
                        else:
                                hypo[k]
                                print(hypo)
                                print("\nThe maximally specific Find-s hypothesis for the given training examples is");
                                list=[]
                                for i in range(d):
                                    list.append(hypo[i])
                                    print(list)



The given training examples are:


ValueError: I/O operation on closed file.

In [3]:
import pandas as pd
import numpy as np
 
#to read the data in the csv file
data = pd.read_csv("ws.csv")
print(data)
 
#making an array of all the attributes
d = np.array(data)[:,:-1]
print("The attributes are: ",d)
 
#segragating the target that has positive and negative examples
target = np.array(data)[:,-1]
print("The target is: ",target)
 
#training function to implement find-s algorithm
def train(c,t):
    for i, val in enumerate(t):
        if val == "Yes":
            specific_hypothesis = c[i].copy()
            break
             
    for i, val in enumerate(c):
        if t[i] == "Yes":
            for x in range(len(specific_hypothesis)):
                if val[x] != specific_hypothesis[x]:
                    specific_hypothesis[x] = '?'
                else:
                    pass
                 
    return specific_hypothesis
 
#obtaining the final hypothesis
print("The final hypothesis is:",train(d,target))

   Sunny  Warm Normal  Strong Warm.1    Same  Yes
0  Sunny  Warm   High  Strong   Warm    Same  Yes
1  Rainy  Cold   High  Strong   Warm  Change   No
2  Sunny  Warm   High  Strong   Cool  Change  Yes
The attributes are:  [['Sunny' 'Warm' 'High' 'Strong' 'Warm' 'Same']
 ['Rainy' 'Cold' 'High' 'Strong' 'Warm' 'Change']
 ['Sunny' 'Warm' 'High' 'Strong' 'Cool' 'Change']]
The target is:  ['Yes' 'No' 'Yes']
The final hypothesis is: ['Sunny' 'Warm' 'High' 'Strong' '?' '?']


In [5]:
import csv
with open("ws.csv") as f:
    csv_file=csv.reader(f)
    data=list(csv_file)
    print(data)
    s=data[1][:-1]
    g=[['?' for i in range(len(s))] for j in range(len(s))]
    for i in data:
        if i[-1]=="Yes":
            for j in range(len(s)):
                if i[j]!=s[j]:
                    s[j]='?'
                    g[j][j]='?'
        elif i[-1]=="No":
            for j in range(len(s)):
                if i[j]!=s[j]:
                    g[j][j]=s[j]
                else:
                    g[j][j]="?"
        print("\nSteps of Candidate Elimination Algorithm",data.index(i)+1)
        print(s)
        print(g)
        gh=[]

for i in g:
 for j in i:
  if j!='?':
   gh.append(i)
   break
print("\nFinal specific hypothesis:\n",s)
print("\nFinal general hypothesis:\n",gh)

[['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', 'Yes'], ['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same', 'Yes'], ['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change', 'No'], ['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change', 'Yes']]

Steps of Candidate Elimination Algorithm 1
['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']
[['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Steps of Candidate Elimination Algorithm 2
['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']
[['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Steps of Candidate Elimination Algorithm 3
['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']
[['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '

In [1]:

#N QUEEN




global N
N = 4
def printSolution(board):
 for i in range(N):
   for j in range(N):
     print (board[i][j], end = " ")
   print()
def isSafe(board, row, col):
 for i in range(col):
   if board[row][i] == 1:
    return False
 for i, j in zip(range(row, -1, -1),range(col, -1, -1)):
   if board[i][j] == 1:
    return False
 for i, j in zip(range(row, N, 1),range(col, -1, -1)):
   if board[i][j] == 1:
    return False
 return True
def solveNQUtil(board, col):
 if col >= N:
   return True
 for i in range(N):
   if isSafe(board, i, col):
     board[i][col] = 1 
     if solveNQUtil(board, col + 1) == True:
       return True
     board[i][col] = 0
 return False
def solveNQ():
 board = [ [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0],
 [0, 0, 0, 0] ]
 if solveNQUtil(board, 0) == False:
   print ("Solution does not exist")
   return False
 printSolution(board)
 return True
solveNQ()

0 0 1 0 
1 0 0 0 
0 0 0 1 
0 1 0 0 


True

In [3]:
def aStarAlgo (start_node, stop_node):
    open_set = set(start_node) 
    closed_set = set() 
    g= {} #store distance from starting node
    parents = {}# parents contains an adjacency map of all nodes 
    #ditance of starting node from itself is zero
    g[start_node] = 0
    #start_node is root node i.e it has no parent nodes
    #so start_node is set to its own parent node
    parents [start_node] = start_node
    
    while len(open_set) > 0:
      n = None 
    #node with Lowest f() is found 
      for v in open_set:
         if n == None or g[v] + heuristic(v) < g[n] + heuristic(n):
            n = v 
            if n == stop_node or Graph_nodes [n] == None: 
                pass
            else: 
                for(m,weight) in get_neighbors (n):
             #nodes 'm' not in first and last set are added to first
             #n is set its parent 
                   if m not in open_set and m not in closed_set:
                        open_set.add(m)
                        parents [m] = n 
                        g[m] = g[n]+ weight
                        #for each node m, compare its distance from start i.e g(m) to the 
                        #from start through n node 
                   else:
                      if g[m] > g[n] + weight:
                        #update g(m)
                         g[m] = g[n] + weight 
                         #change parent of m to n
                         parents [m] = n
                         #if m in closed set, remove and add to open
                         if m in closed_set:
                             closed_set.remove(m)
                             open_set.add(m)
                             if n == None:
                                print('Path does not exist!') 
                                return None
# if the current node is the stop_node
# then we begin reconstruct in the path from it to the start_node
                                if n == stop_node:
                                   path = []
                                   while parents [n] != n:
                                     path.append(n)
                                     n = parents[n]
                                     path.append(start_node)
                                     path.reverse()
                                     print('Path found: {}'.format(path))
                                   return path
# remove n from the open_list, and add it to closed_list
# because all of his neighbors were inspected
                                   open_set.remove(n)
                                   closed_set.add(n)
                                   print('Path does not exist!')
                                   return None
#define fuction to return neighbor and its distance 
#from the passed node 
def get_neighbors (v):
 if v in Graph_nodes:
    return Graph_nodes [v]
 else:
    return None
#for simplicity we LL consider heuristic distances given 
#and this function returns heuristic distance for all nodes 
def heuristic(n):
    H_dist = {
              'A': 11,
              'B': 6,
              'C': 99,
              'D': 1,
              'E': 7,
              'G': 0,
             }
    return H_dist[n]
    #Describe your graph here
    Graph_nodes = {
                   'A': [('B', 2), ('E', 3)],
                   'B': [('C', 1), ('G', 9)],
                   'C': None,
                   'E': [('D', 6)],
                   'D': [('G', 1)],
                   }
    aStarAlgo ('A', 'G')
